// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// HTTPHandler is an autogenerated mock type for the HTTPHandler type
type HTTPHandler struct {
	mock.Mock
}

// Brand provides a mock function with given fields: w, r
func (_m *HTTPHandler) Brand(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// Health provides a mock function with given fields: w, r
func (_m *HTTPHandler) Health(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// Product provides a mock function with given fields: w, r
func (_m *HTTPHandler) Product(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// ProductBrand provides a mock function with given fields: w, r
func (_m *HTTPHandler) ProductBrand(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// Transaction provides a mock function with given fields: w, r
func (_m *HTTPHandler) Transaction(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}
