// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	snowflake "github.com/bwmarrin/snowflake"
	mock "github.com/stretchr/testify/mock"
)

// Snowflake is an autogenerated mock type for the Snowflake type
type Snowflake struct {
	mock.Mock
}

// Generate provides a mock function with given fields:
func (_m *Snowflake) Generate() snowflake.ID {
	ret := _m.Called()

	var r0 snowflake.ID
	if rf, ok := ret.Get(0).(func() snowflake.ID); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(snowflake.ID)
	}

	return r0
}
